[package]
authors = ["Noam Baraz <n0987b@gmail.com>"]
name = "tricone-lang"
version = "0.1.0"

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
lalrpop-util = "0.15.2"
regex = "0.2.1"

[[bin]]
name = "run"
path = "src/bin.rs"
